📋 GERANDO SQL COM TODOS OS DADOS OFICIAIS...
-- ==========================================
-- 🗺️  TODOS OS DISTRITOS DE MOÇAMBIQUE (Nível 2)
-- ==========================================
INSERT INTO mozambique_locations (name, province, district, type, lat, lng) VALUES
('Ancuabe', 'Cabo Delgado', 'Ancuabe', 'district', 0.0, 0.0),
('Balama', 'Cabo Delgado', 'Balama', 'district', 0.0, 0.0),
('Chiure', 'Cabo Delgado', 'Chiure', 'district', 0.0, 0.0),
('Cidade De Pemba', 'Cabo Delgado', 'Cidade De Pemba', 'district', 0.0, 0.0),
('Ibo', 'Cabo Delgado', 'Ibo', 'district', 0.0, 0.0),
('Macomia', 'Cabo Delgado', 'Macomia', 'district', 0.0, 0.0),
('Mecufi', 'Cabo Delgado', 'Mecufi', 'district', 0.0, 0.0),
('Meluco', 'Cabo Delgado', 'Meluco', 'district', 0.0, 0.0),
('Metuge', 'Cabo Delgado', 'Metuge', 'district', 0.0, 0.0),
('Mocimboa Da Praia', 'Cabo Delgado', 'Mocimboa Da Praia', 'district', 0.0, 0.0),
('Montepuez', 'Cabo Delgado', 'Montepuez', 'district', 0.0, 0.0),
('Mueda', 'Cabo Delgado', 'Mueda', 'district', 0.0, 0.0),
('Muidumbe', 'Cabo Delgado', 'Muidumbe', 'district', 0.0, 0.0),
('Namuno', 'Cabo Delgado', 'Namuno', 'district', 0.0, 0.0),
('Nangade', 'Cabo Delgado', 'Nangade', 'district', 0.0, 0.0),
('Palma', 'Cabo Delgado', 'Palma', 'district', 0.0, 0.0),
('Quissanga', 'Cabo Delgado', 'Quissanga', 'district', 0.0, 0.0),
('Bilene', 'Gaza', 'Bilene', 'district', 0.0, 0.0),
('Chibuto', 'Gaza', 'Chibuto', 'district', 0.0, 0.0),
('Chicualacuala', 'Gaza', 'Chicualacuala', 'district', 0.0, 0.0),
('Chigubo', 'Gaza', 'Chigubo', 'district', 0.0, 0.0),
('Chokwe', 'Gaza', 'Chokwe', 'district', 0.0, 0.0),
('Chongoene', 'Gaza', 'Chongoene', 'district', 0.0, 0.0),
('Cidade De Xai-Xai', 'Gaza', 'Cidade De Xai-Xai', 'district', 0.0, 0.0),
('Guija', 'Gaza', 'Guija', 'district', 0.0, 0.0),
('Limpopo', 'Gaza', 'Limpopo', 'district', 0.0, 0.0),
('Mabalane', 'Gaza', 'Mabalane', 'district', 0.0, 0.0),
('Mandlakaze', 'Gaza', 'Mandlakaze', 'district', 0.0, 0.0),
('Mapai', 'Gaza', 'Mapai', 'district', 0.0, 0.0),
('Massangena', 'Gaza', 'Massangena', 'district', 0.0, 0.0),
('Massingir', 'Gaza', 'Massingir', 'district', 0.0, 0.0),
('Cidade De Inhambane', 'Inhambane', 'Cidade De Inhambane', 'district', 0.0, 0.0),
('Funhalouro', 'Inhambane', 'Funhalouro', 'district', 0.0, 0.0),
('Govuro', 'Inhambane', 'Govuro', 'district', 0.0, 0.0),
('Homoine', 'Inhambane', 'Homoine', 'district', 0.0, 0.0),
('Inharrime', 'Inhambane', 'Inharrime', 'district', 0.0, 0.0),
('Inhassoro', 'Inhambane', 'Inhassoro', 'district', 0.0, 0.0),
('Jangamo', 'Inhambane', 'Jangamo', 'district', 0.0, 0.0),
('Mabote', 'Inhambane', 'Mabote', 'district', 0.0, 0.0),
('Massinga', 'Inhambane', 'Massinga', 'district', 0.0, 0.0),
('Maxixe', 'Inhambane', 'Maxixe', 'district', 0.0, 0.0),
('Morrumbene', 'Inhambane', 'Morrumbene', 'district', 0.0, 0.0),
('Panda', 'Inhambane', 'Panda', 'district', 0.0, 0.0),
('Vilankulo', 'Inhambane', 'Vilankulo', 'district', 0.0, 0.0),
('Zavala', 'Inhambane', 'Zavala', 'district', 0.0, 0.0),
('Barue', 'Manica', 'Barue', 'district', 0.0, 0.0),
('Cidade De Chimoio', 'Manica', 'Cidade De Chimoio', 'district', 0.0, 0.0),
('Gondola', 'Manica', 'Gondola', 'district', 0.0, 0.0),
('Guro', 'Manica', 'Guro', 'district', 0.0, 0.0),
('Macate', 'Manica', 'Macate', 'district', 0.0, 0.0),
('Machaze', 'Manica', 'Machaze', 'district', 0.0, 0.0),
('Macossa', 'Manica', 'Macossa', 'district', 0.0, 0.0),
('Manica', 'Manica', 'Manica', 'district', 0.0, 0.0),
('Mossurize', 'Manica', 'Mossurize', 'district', 0.0, 0.0),
('Sussundenga', 'Manica', 'Sussundenga', 'district', 0.0, 0.0),
('Tambara', 'Manica', 'Tambara', 'district', 0.0, 0.0),
('Vanduzi', 'Manica', 'Vanduzi', 'district', 0.0, 0.0),
('Boane', 'Maputo', 'Boane', 'district', 0.0, 0.0),
('Cidade Da Matola', 'Maputo', 'Cidade Da Matola', 'district', 0.0, 0.0),
('Magude', 'Maputo', 'Magude', 'district', 0.0, 0.0),
('Manhiça', 'Maputo', 'Manhiça', 'district', 0.0, 0.0),
('Marracuene', 'Maputo', 'Marracuene', 'district', 0.0, 0.0),
('Matutuine', 'Maputo', 'Matutuine', 'district', 0.0, 0.0),
('Moamba', 'Maputo', 'Moamba', 'district', 0.0, 0.0),
('Namaacha', 'Maputo', 'Namaacha', 'district', 0.0, 0.0),
('Cidade De Maputo', 'Maputo City', 'Cidade De Maputo', 'district', 0.0, 0.0),
('Angoche', 'Nampula', 'Angoche', 'district', 0.0, 0.0),
('Cidade De Nampula', 'Nampula', 'Cidade De Nampula', 'district', 0.0, 0.0),
('Erati', 'Nampula', 'Erati', 'district', 0.0, 0.0),
('Ilha De Moçambique', 'Nampula', 'Ilha De Moçambique', 'district', 0.0, 0.0),
('Lalaua', 'Nampula', 'Lalaua', 'district', 0.0, 0.0),
('Larde', 'Nampula', 'Larde', 'district', 0.0, 0.0),
('Liúpo', 'Nampula', 'Liúpo', 'district', 0.0, 0.0),
('Malema', 'Nampula', 'Malema', 'district', 0.0, 0.0),
('Meconta', 'Nampula', 'Meconta', 'district', 0.0, 0.0),
('Mecuburi', 'Nampula', 'Mecuburi', 'district', 0.0, 0.0),
('Memba', 'Nampula', 'Memba', 'district', 0.0, 0.0),
('Mogincual', 'Nampula', 'Mogincual', 'district', 0.0, 0.0),
('Mogovolas', 'Nampula', 'Mogovolas', 'district', 0.0, 0.0),
('Moma', 'Nampula', 'Moma', 'district', 0.0, 0.0),
('Monapo', 'Nampula', 'Monapo', 'district', 0.0, 0.0),
('Mossuril', 'Nampula', 'Mossuril', 'district', 0.0, 0.0),
('Muecate', 'Nampula', 'Muecate', 'district', 0.0, 0.0),
('Murrupula', 'Nampula', 'Murrupula', 'district', 0.0, 0.0),
('Nacala', 'Nampula', 'Nacala', 'district', 0.0, 0.0),
('Nacala-A-Velha', 'Nampula', 'Nacala-A-Velha', 'district', 0.0, 0.0),
('Nacaroa', 'Nampula', 'Nacaroa', 'district', 0.0, 0.0),
('Rapale', 'Nampula', 'Rapale', 'district', 0.0, 0.0),
('Ribaue', 'Nampula', 'Ribaue', 'district', 0.0, 0.0),
('Chimbonila', 'Niassa', 'Chimbonila', 'district', 0.0, 0.0),
('Cidade De Lichinga', 'Niassa', 'Cidade De Lichinga', 'district', 0.0, 0.0),
('Cuamba', 'Niassa', 'Cuamba', 'district', 0.0, 0.0),
('Ilha Licom', 'Niassa', 'Ilha Licom', 'district', 0.0, 0.0),
('Ilha Risunodo', 'Niassa', 'Ilha Risunodo', 'district', 0.0, 0.0),
('Lago', 'Niassa', 'Lago', 'district', 0.0, 0.0),
('Lago Niassa', 'Niassa', 'Lago Niassa', 'district', 0.0, 0.0),
('Majune', 'Niassa', 'Majune', 'district', 0.0, 0.0),
('Mandimba', 'Niassa', 'Mandimba', 'district', 0.0, 0.0),
('Marrupa', 'Niassa', 'Marrupa', 'district', 0.0, 0.0),
('Maua', 'Niassa', 'Maua', 'district', 0.0, 0.0),
('Mavago', 'Niassa', 'Mavago', 'district', 0.0, 0.0),
('Mecanhelas', 'Niassa', 'Mecanhelas', 'district', 0.0, 0.0),
('Mecula', 'Niassa', 'Mecula', 'district', 0.0, 0.0),
('Metarica', 'Niassa', 'Metarica', 'district', 0.0, 0.0),
('Muembe', 'Niassa', 'Muembe', 'district', 0.0, 0.0),
('Ngauma', 'Niassa', 'Ngauma', 'district', 0.0, 0.0),
('Nipepe', 'Niassa', 'Nipepe', 'district', 0.0, 0.0),
('Sanga', 'Niassa', 'Sanga', 'district', 0.0, 0.0),
('Buzi', 'Sofala', 'Buzi', 'district', 0.0, 0.0),
('Caia', 'Sofala', 'Caia', 'district', 0.0, 0.0),
('Chemba', 'Sofala', 'Chemba', 'district', 0.0, 0.0),
('Cheringoma', 'Sofala', 'Cheringoma', 'district', 0.0, 0.0),
('Chibabava', 'Sofala', 'Chibabava', 'district', 0.0, 0.0),
('Cidade Da Beira', 'Sofala', 'Cidade Da Beira', 'district', 0.0, 0.0),
('Dondo', 'Sofala', 'Dondo', 'district', 0.0, 0.0),
('Gorongosa', 'Sofala', 'Gorongosa', 'district', 0.0, 0.0),
('Machanga', 'Sofala', 'Machanga', 'district', 0.0, 0.0),
('Maringue', 'Sofala', 'Maringue', 'district', 0.0, 0.0),
('Marromeu', 'Sofala', 'Marromeu', 'district', 0.0, 0.0),
('Muanza', 'Sofala', 'Muanza', 'district', 0.0, 0.0),
('Nhamatanda', 'Sofala', 'Nhamatanda', 'district', 0.0, 0.0),
('Angonia', 'Tete', 'Angonia', 'district', 0.0, 0.0),
('Cahora Bassa', 'Tete', 'Cahora Bassa', 'district', 0.0, 0.0),
('Changara', 'Tete', 'Changara', 'district', 0.0, 0.0),
('Chifunde', 'Tete', 'Chifunde', 'district', 0.0, 0.0),
('Chiuta', 'Tete', 'Chiuta', 'district', 0.0, 0.0),
('Cidade De Tete', 'Tete', 'Cidade De Tete', 'district', 0.0, 0.0),
('Doa', 'Tete', 'Doa', 'district', 0.0, 0.0),
('Macanga', 'Tete', 'Macanga', 'district', 0.0, 0.0),
('Magoe', 'Tete', 'Magoe', 'district', 0.0, 0.0),
('Marara', 'Tete', 'Marara', 'district', 0.0, 0.0),
('Maravia', 'Tete', 'Maravia', 'district', 0.0, 0.0),
('Moatize', 'Tete', 'Moatize', 'district', 0.0, 0.0),
('Mutarara', 'Tete', 'Mutarara', 'district', 0.0, 0.0),
('Tsangano', 'Tete', 'Tsangano', 'district', 0.0, 0.0),
('Zumbu', 'Tete', 'Zumbu', 'district', 0.0, 0.0),
('Alto Molocue', 'Zambezia', 'Alto Molocue', 'district', 0.0, 0.0),
('Chinde', 'Zambezia', 'Chinde', 'district', 0.0, 0.0),
('Cidade De Quelimane', 'Zambezia', 'Cidade De Quelimane', 'district', 0.0, 0.0),
('Derre', 'Zambezia', 'Derre', 'district', 0.0, 0.0),
('Gile', 'Zambezia', 'Gile', 'district', 0.0, 0.0),
('Gurue', 'Zambezia', 'Gurue', 'district', 0.0, 0.0),
('Ile', 'Zambezia', 'Ile', 'district', 0.0, 0.0),
('Inhassunge', 'Zambezia', 'Inhassunge', 'district', 0.0, 0.0),
('Luabo', 'Zambezia', 'Luabo', 'district', 0.0, 0.0),
('Lugela', 'Zambezia', 'Lugela', 'district', 0.0, 0.0),
('Maganja Da Costa', 'Zambezia', 'Maganja Da Costa', 'district', 0.0, 0.0),
('Maquival', 'Zambezia', 'Maquival', 'district', 0.0, 0.0),
('Milange', 'Zambezia', 'Milange', 'district', 0.0, 0.0),
('Mocuba', 'Zambezia', 'Mocuba', 'district', 0.0, 0.0),
('Mocubela', 'Zambezia', 'Mocubela', 'district', 0.0, 0.0),
('Molumbo', 'Zambezia', 'Molumbo', 'district', 0.0, 0.0),
('Mopeia', 'Zambezia', 'Mopeia', 'district', 0.0, 0.0),
('Morrumbala', 'Zambezia', 'Morrumbala', 'district', 0.0, 0.0),
('Mulevala', 'Zambezia', 'Mulevala', 'district', 0.0, 0.0),
('Namacurra', 'Zambezia', 'Namacurra', 'district', 0.0, 0.0),
('Namarroi', 'Zambezia', 'Namarroi', 'district', 0.0, 0.0),
('Nicoadala', 'Zambezia', 'Nicoadala', 'district', 0.0, 0.0),
('Pebane', 'Zambezia', 'Pebane', 'district', 0.0, 0.0),

-- ==========================================
-- 🏘️  TODOS OS BAIRROS/LOCALIDADES (Nível 3)
-- ==========================================
INSERT INTO mozambique_locations (name, province, district, type, lat, lng) VALUES
('Ancuabe', 'Cabo Delgado', 'Ancuabe', 'neighbourhood', 0.0, 0.0),
('Mesa', 'Cabo Delgado', 'Ancuabe', 'neighbourhood', 0.0, 0.0),
('Metoro', 'Cabo Delgado', 'Ancuabe', 'neighbourhood', 0.0, 0.0),
('Balama', 'Cabo Delgado', 'Balama', 'neighbourhood', 0.0, 0.0),
('Impiri', 'Cabo Delgado', 'Balama', 'neighbourhood', 0.0, 0.0),
('Kuekue', 'Cabo Delgado', 'Balama', 'neighbourhood', 0.0, 0.0),
('Mavala', 'Cabo Delgado', 'Balama', 'neighbourhood', 0.0, 0.0),
('Chiure', 'Cabo Delgado', 'Chiure', 'neighbourhood', 0.0, 0.0),
('Chiure Velho', 'Cabo Delgado', 'Chiure', 'neighbourhood', 0.0, 0.0),
('Katapua', 'Cabo Delgado', 'Chiure', 'neighbourhood', 0.0, 0.0),
('Mazeze', 'Cabo Delgado', 'Chiure', 'neighbourhood', 0.0, 0.0),
('Namogelia', 'Cabo Delgado', 'Chiure', 'neighbourhood', 0.0, 0.0),
('Ocua', 'Cabo Delgado', 'Chiure', 'neighbourhood', 0.0, 0.0),
('Cidade De Pemba', 'Cabo Delgado', 'Cidade De Pemba', 'neighbourhood', 0.0, 0.0),
('Ibo', 'Cabo Delgado', 'Ibo', 'neighbourhood', 0.0, 0.0),
('Quirimba', 'Cabo Delgado', 'Ibo', 'neighbourhood', 0.0, 0.0),
('Chai', 'Cabo Delgado', 'Macomia', 'neighbourhood', 0.0, 0.0),
('Macomia', 'Cabo Delgado', 'Macomia', 'neighbourhood', 0.0, 0.0),
('Mucojo', 'Cabo Delgado', 'Macomia', 'neighbourhood', 0.0, 0.0),
('Quiterajo', 'Cabo Delgado', 'Macomia', 'neighbourhood', 0.0, 0.0),
('Mecufi', 'Cabo Delgado', 'Mecufi', 'neighbourhood', 0.0, 0.0),
('Murrebue', 'Cabo Delgado', 'Mecufi', 'neighbourhood', 0.0, 0.0),
('Meluco', 'Cabo Delgado', 'Meluco', 'neighbourhood', 0.0, 0.0),
('Muaguide', 'Cabo Delgado', 'Meluco', 'neighbourhood', 0.0, 0.0),
('Metuge', 'Cabo Delgado', 'Metuge', 'neighbourhood', 0.0, 0.0),
('Mieze', 'Cabo Delgado', 'Metuge', 'neighbourhood', 0.0, 0.0),
('Diaca', 'Cabo Delgado', 'Mocimboa Da Praia', 'neighbourhood', 0.0, 0.0),
('Mbau', 'Cabo Delgado', 'Mocimboa Da Praia', 'neighbourhood', 0.0, 0.0),
('Mocimboa Da Praia', 'Cabo Delgado', 'Mocimboa Da Praia', 'neighbourhood', 0.0, 0.0),
('Mapupulo', 'Cabo Delgado', 'Montepuez', 'neighbourhood', 0.0, 0.0),
('Mirate', 'Cabo Delgado', 'Montepuez', 'neighbourhood', 0.0, 0.0),
('Montepuez', 'Cabo Delgado', 'Montepuez', 'neighbourhood', 0.0, 0.0),
('Nairoto', 'Cabo Delgado', 'Montepuez', 'neighbourhood', 0.0, 0.0),
('Namanhumbir', 'Cabo Delgado', 'Montepuez', 'neighbourhood', 0.0, 0.0),
('Chapa', 'Cabo Delgado', 'Mueda', 'neighbourhood', 0.0, 0.0),
('Imbuo', 'Cabo Delgado', 'Mueda', 'neighbourhood', 0.0, 0.0),
('Mueda', 'Cabo Delgado', 'Mueda', 'neighbourhood', 0.0, 0.0),
('N'Gapa', 'Cabo Delgado', 'Mueda', 'neighbourhood', 0.0, 0.0),
('Negomano', 'Cabo Delgado', 'Mueda', 'neighbourhood', 0.0, 0.0),
('Chitunda', 'Cabo Delgado', 'Muidumbe', 'neighbourhood', 0.0, 0.0),
('Miteda', 'Cabo Delgado', 'Muidumbe', 'neighbourhood', 0.0, 0.0),
('Muidumbe', 'Cabo Delgado', 'Muidumbe', 'neighbourhood', 0.0, 0.0),
('Hucula', 'Cabo Delgado', 'Namuno', 'neighbourhood', 0.0, 0.0),
('Machoca', 'Cabo Delgado', 'Namuno', 'neighbourhood', 0.0, 0.0),
('Meloco', 'Cabo Delgado', 'Namuno', 'neighbourhood', 0.0, 0.0),
('N'Cumpe', 'Cabo Delgado', 'Namuno', 'neighbourhood', 0.0, 0.0),
('Namuno', 'Cabo Delgado', 'Namuno', 'neighbourhood', 0.0, 0.0),
('Papai', 'Cabo Delgado', 'Namuno', 'neighbourhood', 0.0, 0.0),
('M'Tamba', 'Cabo Delgado', 'Nangade', 'neighbourhood', 0.0, 0.0),
('Nangade', 'Cabo Delgado', 'Nangade', 'neighbourhood', 0.0, 0.0),
('Olumbi', 'Cabo Delgado', 'Palma', 'neighbourhood', 0.0, 0.0),
('Palma', 'Cabo Delgado', 'Palma', 'neighbourhood', 0.0, 0.0),
('Pundanhar', 'Cabo Delgado', 'Palma', 'neighbourhood', 0.0, 0.0),
('Quionga', 'Cabo Delgado', 'Palma', 'neighbourhood', 0.0, 0.0),
('Bilibiza', 'Cabo Delgado', 'Quissanga', 'neighbourhood', 0.0, 0.0),
('Mahate', 'Cabo Delgado', 'Quissanga', 'neighbourhood', 0.0, 0.0),
('Quissanga', 'Cabo Delgado', 'Quissanga', 'neighbourhood', 0.0, 0.0),
('Macia', 'Gaza', 'Bilene', 'neighbourhood', 0.0, 0.0),
('Makluane', 'Gaza', 'Bilene', 'neighbourhood', 0.0, 0.0),
('Mazivila', 'Gaza', 'Bilene', 'neighbourhood', 0.0, 0.0),
('Messano', 'Gaza', 'Bilene', 'neighbourhood', 0.0, 0.0),
('Praia De Bilene', 'Gaza', 'Bilene', 'neighbourhood', 0.0, 0.0),
('Alto Changane', 'Gaza', 'Chibuto', 'neighbourhood', 0.0, 0.0),
('Chaimite', 'Gaza', 'Chibuto', 'neighbourhood', 0.0, 0.0),
('Changanine', 'Gaza', 'Chibuto', 'neighbourhood', 0.0, 0.0),
('Chibuto', 'Gaza', 'Chibuto', 'neighbourhood', 0.0, 0.0),
('Godide', 'Gaza', 'Chibuto', 'neighbourhood', 0.0, 0.0),
('Malehice', 'Gaza', 'Chibuto', 'neighbourhood', 0.0, 0.0),
('Pafuri', 'Gaza', 'Chicualacuala', 'neighbourhood', 0.0, 0.0),
('Vila Eduardo Mondlane', 'Gaza', 'Chicualacuala', 'neighbourhood', 0.0, 0.0),
('Chigubo', 'Gaza', 'Chigubo', 'neighbourhood', 0.0, 0.0),
('Dindiza', 'Gaza', 'Chigubo', 'neighbourhood', 0.0, 0.0),
('Chokwe', 'Gaza', 'Chokwe', 'neighbourhood', 0.0, 0.0),
('Lionde', 'Gaza', 'Chokwe', 'neighbourhood', 0.0, 0.0),
('Macarretane', 'Gaza', 'Chokwe', 'neighbourhood', 0.0, 0.0),
('Xilembene', 'Gaza', 'Chokwe', 'neighbourhood', 0.0, 0.0),
('Chongoene', 'Gaza', 'Chongoene', 'neighbourhood', 0.0, 0.0),
('Madzucane', 'Gaza', 'Chongoene', 'neighbourhood', 0.0, 0.0),
('Nguzene', 'Gaza', 'Chongoene', 'neighbourhood', 0.0, 0.0),
('Cidade De Xai-Xai', 'Gaza', 'Cidade De Xai-Xai', 'neighbourhood', 0.0, 0.0),
('Caniçado', 'Gaza', 'Guija', 'neighbourhood', 0.0, 0.0),
('Chivongoene', 'Gaza', 'Guija', 'neighbourhood', 0.0, 0.0),
('Mubangoene', 'Gaza', 'Guija', 'neighbourhood', 0.0, 0.0),
('Nalazi', 'Gaza', 'Guija', 'neighbourhood', 0.0, 0.0),
('Chicumbane', 'Gaza', 'Limpopo', 'neighbourhood', 0.0, 0.0),
('Chissano', 'Gaza', 'Limpopo', 'neighbourhood', 0.0, 0.0),
('Zongoene', 'Gaza', 'Limpopo', 'neighbourhood', 0.0, 0.0),
('Combomune', 'Gaza', 'Mabalane', 'neighbourhood', 0.0, 0.0),
('Mabalane', 'Gaza', 'Mabalane', 'neighbourhood', 0.0, 0.0),
('Ntlavene', 'Gaza', 'Mabalane', 'neighbourhood', 0.0, 0.0),
('Chibonzane', 'Gaza', 'Mandlakaze', 'neighbourhood', 0.0, 0.0),
('Chidenguele', 'Gaza', 'Mandlakaze', 'neighbourhood', 0.0, 0.0),
('Macuacua', 'Gaza', 'Mandlakaze', 'neighbourhood', 0.0, 0.0),
('Mandlakaze', 'Gaza', 'Mandlakaze', 'neighbourhood', 0.0, 0.0),
('Xhalala', 'Gaza', 'Mandlakaze', 'neighbourhood', 0.0, 0.0),
('Mapai', 'Gaza', 'Mapai', 'neighbourhood', 0.0, 0.0),
('Massangena', 'Gaza', 'Massangena', 'neighbourhood', 0.0, 0.0),
('Mavue', 'Gaza', 'Massangena', 'neighbourhood', 0.0, 0.0),
('Massingir', 'Gaza', 'Massingir', 'neighbourhood', 0.0, 0.0),
('Mavodze', 'Gaza', 'Massingir', 'neighbourhood', 0.0, 0.0),
('Zulo', 'Gaza', 'Massingir', 'neighbourhood', 0.0, 0.0),
('Cidade De Inhambane', 'Inhambane', 'Cidade De Inhambane', 'neighbourhood', 0.0, 0.0),
('Funhalouro', 'Inhambane', 'Funhalouro', 'neighbourhood', 0.0, 0.0),
('Tome', 'Inhambane', 'Funhalouro', 'neighbourhood', 0.0, 0.0),
('Nova Mambone', 'Inhambane', 'Govuro', 'neighbourhood', 0.0, 0.0),
('Save', 'Inhambane', 'Govuro', 'neighbourhood', 0.0, 0.0),
('Homoine', 'Inhambane', 'Homoine', 'neighbourhood', 0.0, 0.0),
('Pembe', 'Inhambane', 'Homoine', 'neighbourhood', 0.0, 0.0),
('Inharrime', 'Inhambane', 'Inharrime', 'neighbourhood', 0.0, 0.0),
('Mocumbi', 'Inhambane', 'Inharrime', 'neighbourhood', 0.0, 0.0),
('Bazaruto', 'Inhambane', 'Inhassoro', 'neighbourhood', 0.0, 0.0),
('Inhassoro', 'Inhambane', 'Inhassoro', 'neighbourhood', 0.0, 0.0),
('Cumbana', 'Inhambane', 'Jangamo', 'neighbourhood', 0.0, 0.0),
('Jangamo', 'Inhambane', 'Jangamo', 'neighbourhood', 0.0, 0.0),
('Mabote', 'Inhambane', 'Mabote', 'neighbourhood', 0.0, 0.0),
('Zimane', 'Inhambane', 'Mabote', 'neighbourhood', 0.0, 0.0),
('Zinave', 'Inhambane', 'Mabote', 'neighbourhood', 0.0, 0.0),
('Chicomo', 'Inhambane', 'Massinga', 'neighbourhood', 0.0, 0.0),
('Massinga', 'Inhambane', 'Massinga', 'neighbourhood', 0.0, 0.0),
('Maxixe', 'Inhambane', 'Maxixe', 'neighbourhood', 0.0, 0.0),
('Morrumbene', 'Inhambane', 'Morrumbene', 'neighbourhood', 0.0, 0.0),
('Mucoduene', 'Inhambane', 'Morrumbene', 'neighbourhood', 0.0, 0.0),
('Mawayela', 'Inhambane', 'Panda', 'neighbourhood', 0.0, 0.0),
('Panda', 'Inhambane', 'Panda', 'neighbourhood', 0.0, 0.0),
('Urrene', 'Inhambane', 'Panda', 'neighbourhood', 0.0, 0.0),
('Mapinhane', 'Inhambane', 'Vilankulo', 'neighbourhood', 0.0, 0.0),
('Vilankulo', 'Inhambane', 'Vilankulo', 'neighbourhood', 0.0, 0.0),
('Quissico', 'Inhambane', 'Zavala', 'neighbourhood', 0.0, 0.0),
('Zandamela', 'Inhambane', 'Zavala', 'neighbourhood', 0.0, 0.0),
('Catandica', 'Manica', 'Barue', 'neighbourhood', 0.0, 0.0),
('Choa', 'Manica', 'Barue', 'neighbourhood', 0.0, 0.0),
('Nhampassa', 'Manica', 'Barue', 'neighbourhood', 0.0, 0.0),
('Cidade De Chimoio', 'Manica', 'Cidade De Chimoio', 'neighbourhood', 0.0, 0.0),
('Amatongas', 'Manica', 'Gondola', 'neighbourhood', 0.0, 0.0),
('Cafumpe', 'Manica', 'Gondola', 'neighbourhood', 0.0, 0.0),
('Gondola', 'Manica', 'Gondola', 'neighbourhood', 0.0, 0.0),
('Inchope', 'Manica', 'Gondola', 'neighbourhood', 0.0, 0.0),
('Guro', 'Manica', 'Guro', 'neighbourhood', 0.0, 0.0),
('Mandie', 'Manica', 'Guro', 'neighbourhood', 0.0, 0.0),
('Mungari', 'Manica', 'Guro', 'neighbourhood', 0.0, 0.0),
('Nhamassonge', 'Manica', 'Guro', 'neighbourhood', 0.0, 0.0),
('Macate', 'Manica', 'Macate', 'neighbourhood', 0.0, 0.0),
('Zembe', 'Manica', 'Macate', 'neighbourhood', 0.0, 0.0),
('Chitobe', 'Manica', 'Machaze', 'neighbourhood', 0.0, 0.0),
('Save', 'Manica', 'Machaze', 'neighbourhood', 0.0, 0.0),
('Macossa', 'Manica', 'Macossa', 'neighbourhood', 0.0, 0.0),
('Nguawala', 'Manica', 'Macossa', 'neighbourhood', 0.0, 0.0),
('Nhamagua', 'Manica', 'Macossa', 'neighbourhood', 0.0, 0.0),
('Machipanda', 'Manica', 'Manica', 'neighbourhood', 0.0, 0.0),
('Manica', 'Manica', 'Manica', 'neighbourhood', 0.0, 0.0),
('Mavonde', 'Manica', 'Manica', 'neighbourhood', 0.0, 0.0),
('Messica', 'Manica', 'Manica', 'neighbourhood', 0.0, 0.0),
('Chiurairue', 'Manica', 'Mossurize', 'neighbourhood', 0.0, 0.0),
('Dacata', 'Manica', 'Mossurize', 'neighbourhood', 0.0, 0.0),
('Espungabera', 'Manica', 'Mossurize', 'neighbourhood', 0.0, 0.0),
('Dombe', 'Manica', 'Sussundenga', 'neighbourhood', 0.0, 0.0),
('Muoha', 'Manica', 'Sussundenga', 'neighbourhood', 0.0, 0.0),
('Rotanda', 'Manica', 'Sussundenga', 'neighbourhood', 0.0, 0.0),
('Sussundenga', 'Manica', 'Sussundenga', 'neighbourhood', 0.0, 0.0),
('Bazua', 'Manica', 'Tambara', 'neighbourhood', 0.0, 0.0),
('Nhacafula', 'Manica', 'Tambara', 'neighbourhood', 0.0, 0.0),
('Nhacolo', 'Manica', 'Tambara', 'neighbourhood', 0.0, 0.0),
('Matsinho', 'Manica', 'Vanduzi', 'neighbourhood', 0.0, 0.0),
('Vanduzi', 'Manica', 'Vanduzi', 'neighbourhood', 0.0, 0.0),
('Boane', 'Maputo', 'Boane', 'neighbourhood', 0.0, 0.0),
('Matola Rio', 'Maputo', 'Boane', 'neighbourhood', 0.0, 0.0),
('Cidade Da Matola', 'Maputo', 'Cidade Da Matola', 'neighbourhood', 0.0, 0.0),
('Magude', 'Maputo', 'Magude', 'neighbourhood', 0.0, 0.0),
('Mahele', 'Maputo', 'Magude', 'neighbourhood', 0.0, 0.0),
('Mapulanguene', 'Maputo', 'Magude', 'neighbourhood', 0.0, 0.0),
('Motaze', 'Maputo', 'Magude', 'neighbourhood', 0.0, 0.0),
('Panjane', 'Maputo', 'Magude', 'neighbourhood', 0.0, 0.0),
('Calanga', 'Maputo', 'Manhiça', 'neighbourhood', 0.0, 0.0),
('Ilha Josina Machel', 'Maputo', 'Manhiça', 'neighbourhood', 0.0, 0.0),
('Maluana', 'Maputo', 'Manhiça', 'neighbourhood', 0.0, 0.0),
('Manhiça', 'Maputo', 'Manhiça', 'neighbourhood', 0.0, 0.0),
('Palmeira', 'Maputo', 'Manhiça', 'neighbourhood', 0.0, 0.0),
('Xinavane', 'Maputo', 'Manhiça', 'neighbourhood', 0.0, 0.0),
('Machubo', 'Maputo', 'Marracuene', 'neighbourhood', 0.0, 0.0),
('Marracuene', 'Maputo', 'Marracuene', 'neighbourhood', 0.0, 0.0),
('Bela Vista', 'Maputo', 'Matutuine', 'neighbourhood', 0.0, 0.0),
('Catuane', 'Maputo', 'Matutuine', 'neighbourhood', 0.0, 0.0),
('Mugazine', 'Maputo', 'Matutuine', 'neighbourhood', 0.0, 0.0),
('Ndelane', 'Maputo', 'Matutuine', 'neighbourhood', 0.0, 0.0),
('Zitundo', 'Maputo', 'Matutuine', 'neighbourhood', 0.0, 0.0),
('Moamba', 'Maputo', 'Moamba', 'neighbourhood', 0.0, 0.0),
('Pessene', 'Maputo', 'Moamba', 'neighbourhood', 0.0, 0.0),
('Ressano Garcia', 'Maputo', 'Moamba', 'neighbourhood', 0.0, 0.0),
('Sabie', 'Maputo', 'Moamba', 'neighbourhood', 0.0, 0.0),
('Changalane', 'Maputo', 'Namaacha', 'neighbourhood', 0.0, 0.0),
('Namaacha', 'Maputo', 'Namaacha', 'neighbourhood', 0.0, 0.0),
('Cidade De Maputo', 'Maputo City', 'Cidade De Maputo', 'neighbourhood', 0.0, 0.0),
('Angoche', 'Nampula', 'Angoche', 'neighbourhood', 0.0, 0.0),
('Aube', 'Nampula', 'Angoche', 'neighbourhood', 0.0, 0.0),
('Boila', 'Nampula', 'Angoche', 'neighbourhood', 0.0, 0.0),
('Namaponda', 'Nampula', 'Angoche', 'neighbourhood', 0.0, 0.0),
('Cidade De Nampula', 'Nampula', 'Cidade De Nampula', 'neighbourhood', 0.0, 0.0),
('Alua', 'Nampula', 'Erati', 'neighbourhood', 0.0, 0.0),
('Namapa', 'Nampula', 'Erati', 'neighbourhood', 0.0, 0.0),
('Namiroa', 'Nampula', 'Erati', 'neighbourhood', 0.0, 0.0),
('Ilha De Moçambique', 'Nampula', 'Ilha De Moçambique', 'neighbourhood', 0.0, 0.0),
('Lumbo', 'Nampula', 'Ilha De Moçambique', 'neighbourhood', 0.0, 0.0),
('Lalaua', 'Nampula', 'Lalaua', 'neighbourhood', 0.0, 0.0),
('Meti', 'Nampula', 'Lalaua', 'neighbourhood', 0.0, 0.0),
('Larde', 'Nampula', 'Larde', 'neighbourhood', 0.0, 0.0),
('Mucuali', 'Nampula', 'Larde', 'neighbourhood', 0.0, 0.0),
('Liúpo', 'Nampula', 'Liúpo', 'neighbourhood', 0.0, 0.0),
('Quinga', 'Nampula', 'Liúpo', 'neighbourhood', 0.0, 0.0),
('Chihulo', 'Nampula', 'Malema', 'neighbourhood', 0.0, 0.0),
('Malema', 'Nampula', 'Malema', 'neighbourhood', 0.0, 0.0),
('Mutuali', 'Nampula', 'Malema', 'neighbourhood', 0.0, 0.0),
('7 De Abril', 'Nampula', 'Meconta', 'neighbourhood', 0.0, 0.0),
('Corrane', 'Nampula', 'Meconta', 'neighbourhood', 0.0, 0.0),
('Meconta', 'Nampula', 'Meconta', 'neighbourhood', 0.0, 0.0),
('Namialo', 'Nampula', 'Meconta', 'neighbourhood', 0.0, 0.0),
('Mecuburi', 'Nampula', 'Mecuburi', 'neighbourhood', 0.0, 0.0),
('Milhana', 'Nampula', 'Mecuburi', 'neighbourhood', 0.0, 0.0),
('Muite', 'Nampula', 'Mecuburi', 'neighbourhood', 0.0, 0.0),
('Namina', 'Nampula', 'Mecuburi', 'neighbourhood', 0.0, 0.0),
('Chipene', 'Nampula', 'Memba', 'neighbourhood', 0.0, 0.0),
('Lurio', 'Nampula', 'Memba', 'neighbourhood', 0.0, 0.0),
('Mazula', 'Nampula', 'Memba', 'neighbourhood', 0.0, 0.0),
('Memba', 'Nampula', 'Memba', 'neighbourhood', 0.0, 0.0),
('Namige', 'Nampula', 'Mogincual', 'neighbourhood', 0.0, 0.0),
('Quixaxe', 'Nampula', 'Mogincual', 'neighbourhood', 0.0, 0.0),
('Calipo', 'Nampula', 'Mogovolas', 'neighbourhood', 0.0, 0.0),
('Iuluti', 'Nampula', 'Mogovolas', 'neighbourhood', 0.0, 0.0),
('Muatua', 'Nampula', 'Mogovolas', 'neighbourhood', 0.0, 0.0),
('Nametil', 'Nampula', 'Mogovolas', 'neighbourhood', 0.0, 0.0),
('Nanhupo Rio', 'Nampula', 'Mogovolas', 'neighbourhood', 0.0, 0.0),
('Chalaua', 'Nampula', 'Moma', 'neighbourhood', 0.0, 0.0),
('Moma', 'Nampula', 'Moma', 'neighbourhood', 0.0, 0.0),
('Itoculo', 'Nampula', 'Monapo', 'neighbourhood', 0.0, 0.0),
('Monapo', 'Nampula', 'Monapo', 'neighbourhood', 0.0, 0.0),
('Netia', 'Nampula', 'Monapo', 'neighbourhood', 0.0, 0.0),
('Lunga', 'Nampula', 'Mossuril', 'neighbourhood', 0.0, 0.0),
('Matibane', 'Nampula', 'Mossuril', 'neighbourhood', 0.0, 0.0),
('Mossuril', 'Nampula', 'Mossuril', 'neighbourhood', 0.0, 0.0),
('Imala', 'Nampula', 'Muecate', 'neighbourhood', 0.0, 0.0),
('Muculoene', 'Nampula', 'Muecate', 'neighbourhood', 0.0, 0.0),
('Muecate', 'Nampula', 'Muecate', 'neighbourhood', 0.0, 0.0),
('Chinga', 'Nampula', 'Murrupula', 'neighbourhood', 0.0, 0.0),
('Murrupula', 'Nampula', 'Murrupula', 'neighbourhood', 0.0, 0.0),
('Nihessiue', 'Nampula', 'Murrupula', 'neighbourhood', 0.0, 0.0),
('Nacala', 'Nampula', 'Nacala', 'neighbourhood', 0.0, 0.0),
('Covo', 'Nampula', 'Nacala-A-Velha', 'neighbourhood', 0.0, 0.0),
('Nacala-A-Velha', 'Nampula', 'Nacala-A-Velha', 'neighbourhood', 0.0, 0.0),
('Intete', 'Nampula', 'Nacaroa', 'neighbourhood', 0.0, 0.0),
('Nacaroa', 'Nampula', 'Nacaroa', 'neighbourhood', 0.0, 0.0),
('Saua-Saua', 'Nampula', 'Nacaroa', 'neighbourhood', 0.0, 0.0),
('Anchilo', 'Nampula', 'Rapale', 'neighbourhood', 0.0, 0.0),
('Mutivasse', 'Nampula', 'Rapale', 'neighbourhood', 0.0, 0.0),
('Namaita', 'Nampula', 'Rapale', 'neighbourhood', 0.0, 0.0),
('Rapale', 'Nampula', 'Rapale', 'neighbourhood', 0.0, 0.0),
('Cunle', 'Nampula', 'Ribaue', 'neighbourhood', 0.0, 0.0),
('Iapala', 'Nampula', 'Ribaue', 'neighbourhood', 0.0, 0.0),
('Ribaue', 'Nampula', 'Ribaue', 'neighbourhood', 0.0, 0.0),
('Chimbonila', 'Niassa', 'Chimbonila', 'neighbourhood', 0.0, 0.0),
('Lione', 'Niassa', 'Chimbonila', 'neighbourhood', 0.0, 0.0),
('Meponda', 'Niassa', 'Chimbonila', 'neighbourhood', 0.0, 0.0),
('Cidade De Lichinga', 'Niassa', 'Cidade De Lichinga', 'neighbourhood', 0.0, 0.0),
('Cuamba', 'Niassa', 'Cuamba', 'neighbourhood', 0.0, 0.0),
('Etarara', 'Niassa', 'Cuamba', 'neighbourhood', 0.0, 0.0),
('Lurio', 'Niassa', 'Cuamba', 'neighbourhood', 0.0, 0.0),
('Ilha Licom', 'Niassa', 'Ilha Licom', 'neighbourhood', 0.0, 0.0),
('Ilha Risunodo', 'Niassa', 'Ilha Risunodo', 'neighbourhood', 0.0, 0.0),
('Cobue', 'Niassa', 'Lago', 'neighbourhood', 0.0, 0.0),
('Lunho', 'Niassa', 'Lago', 'neighbourhood', 0.0, 0.0),
('Maniamba', 'Niassa', 'Lago', 'neighbourhood', 0.0, 0.0),
('Metangula', 'Niassa', 'Lago', 'neighbourhood', 0.0, 0.0),
('Lago Niassa', 'Niassa', 'Lago Niassa', 'neighbourhood', 0.0, 0.0),
('Malanga', 'Niassa', 'Majune', 'neighbourhood', 0.0, 0.0),
('Muaquia', 'Niassa', 'Majune', 'neighbourhood', 0.0, 0.0),
('Nairrubi', 'Niassa', 'Majune', 'neighbourhood', 0.0, 0.0),
('Mandimba', 'Niassa', 'Mandimba', 'neighbourhood', 0.0, 0.0),
('Mitande', 'Niassa', 'Mandimba', 'neighbourhood', 0.0, 0.0),
('Marangira', 'Niassa', 'Marrupa', 'neighbourhood', 0.0, 0.0),
('Marrupa', 'Niassa', 'Marrupa', 'neighbourhood', 0.0, 0.0),
('Nungo', 'Niassa', 'Marrupa', 'neighbourhood', 0.0, 0.0),
('Maiaca', 'Niassa', 'Maua', 'neighbourhood', 0.0, 0.0),
('Maua', 'Niassa', 'Maua', 'neighbourhood', 0.0, 0.0),
('M'Sawize', 'Niassa', 'Mavago', 'neighbourhood', 0.0, 0.0),
('Mavago', 'Niassa', 'Mavago', 'neighbourhood', 0.0, 0.0),
('Chiuta', 'Niassa', 'Mecanhelas', 'neighbourhood', 0.0, 0.0),
('Insaca', 'Niassa', 'Mecanhelas', 'neighbourhood', 0.0, 0.0),
('Matondovela', 'Niassa', 'Mecula', 'neighbourhood', 0.0, 0.0),
('Mecula', 'Niassa', 'Mecula', 'neighbourhood', 0.0, 0.0),
('Metarica', 'Niassa', 'Metarica', 'neighbourhood', 0.0, 0.0),
('Nacumua', 'Niassa', 'Metarica', 'neighbourhood', 0.0, 0.0),
('Chiconono', 'Niassa', 'Muembe', 'neighbourhood', 0.0, 0.0),
('Muembe', 'Niassa', 'Muembe', 'neighbourhood', 0.0, 0.0),
('Itepela', 'Niassa', 'Ngauma', 'neighbourhood', 0.0, 0.0),
('Massangulo', 'Niassa', 'Ngauma', 'neighbourhood', 0.0, 0.0),
('Muipite', 'Niassa', 'Nipepe', 'neighbourhood', 0.0, 0.0),
('Nipepe', 'Niassa', 'Nipepe', 'neighbourhood', 0.0, 0.0),
('Lussimbesse', 'Niassa', 'Sanga', 'neighbourhood', 0.0, 0.0),
('Macaloge', 'Niassa', 'Sanga', 'neighbourhood', 0.0, 0.0),
('Matchedje', 'Niassa', 'Sanga', 'neighbourhood', 0.0, 0.0),
('Unango', 'Niassa', 'Sanga', 'neighbourhood', 0.0, 0.0),
('Buzi', 'Sofala', 'Buzi', 'neighbourhood', 0.0, 0.0),
('Estaquinha', 'Sofala', 'Buzi', 'neighbourhood', 0.0, 0.0),
('Sofala', 'Sofala', 'Buzi', 'neighbourhood', 0.0, 0.0),
('Caia', 'Sofala', 'Caia', 'neighbourhood', 0.0, 0.0),
('Murraça', 'Sofala', 'Caia', 'neighbourhood', 0.0, 0.0),
('Sena', 'Sofala', 'Caia', 'neighbourhood', 0.0, 0.0),
('Chemba', 'Sofala', 'Chemba', 'neighbourhood', 0.0, 0.0),
('Chiramba', 'Sofala', 'Chemba', 'neighbourhood', 0.0, 0.0),
('Mulima', 'Sofala', 'Chemba', 'neighbourhood', 0.0, 0.0),
('Inhaminga', 'Sofala', 'Cheringoma', 'neighbourhood', 0.0, 0.0),
('Inhamitanga', 'Sofala', 'Cheringoma', 'neighbourhood', 0.0, 0.0),
('Chibabava', 'Sofala', 'Chibabava', 'neighbourhood', 0.0, 0.0),
('Goonda', 'Sofala', 'Chibabava', 'neighbourhood', 0.0, 0.0),
('Muxungue', 'Sofala', 'Chibabava', 'neighbourhood', 0.0, 0.0),
('Cidade Da Beira', 'Sofala', 'Cidade Da Beira', 'neighbourhood', 0.0, 0.0),
('Dondo', 'Sofala', 'Dondo', 'neighbourhood', 0.0, 0.0),
('Mafambisse', 'Sofala', 'Dondo', 'neighbourhood', 0.0, 0.0),
('Gorongosa', 'Sofala', 'Gorongosa', 'neighbourhood', 0.0, 0.0),
('Nhamadze', 'Sofala', 'Gorongosa', 'neighbourhood', 0.0, 0.0),
('Vanduzi', 'Sofala', 'Gorongosa', 'neighbourhood', 0.0, 0.0),
('Divinhe', 'Sofala', 'Machanga', 'neighbourhood', 0.0, 0.0),
('Machanga', 'Sofala', 'Machanga', 'neighbourhood', 0.0, 0.0),
('Canxixe', 'Sofala', 'Maringue', 'neighbourhood', 0.0, 0.0),
('Maringue', 'Sofala', 'Maringue', 'neighbourhood', 0.0, 0.0),
('Subwe', 'Sofala', 'Maringue', 'neighbourhood', 0.0, 0.0),
('Chupanga', 'Sofala', 'Marromeu', 'neighbourhood', 0.0, 0.0),
('Marromeu', 'Sofala', 'Marromeu', 'neighbourhood', 0.0, 0.0),
('Galinha', 'Sofala', 'Muanza', 'neighbourhood', 0.0, 0.0),
('Muanza', 'Sofala', 'Muanza', 'neighbourhood', 0.0, 0.0),
('Nhamatanda', 'Sofala', 'Nhamatanda', 'neighbourhood', 0.0, 0.0),
('Tica', 'Sofala', 'Nhamatanda', 'neighbourhood', 0.0, 0.0),
('Domue', 'Tete', 'Angonia', 'neighbourhood', 0.0, 0.0),
('Ulongue', 'Tete', 'Angonia', 'neighbourhood', 0.0, 0.0),
('Chintholo', 'Tete', 'Cahora Bassa', 'neighbourhood', 0.0, 0.0),
('Chitima', 'Tete', 'Cahora Bassa', 'neighbourhood', 0.0, 0.0),
('Songo', 'Tete', 'Cahora Bassa', 'neighbourhood', 0.0, 0.0),
('Chipembere', 'Tete', 'Changara', 'neighbourhood', 0.0, 0.0),
('Luenha', 'Tete', 'Changara', 'neighbourhood', 0.0, 0.0),
('Chifunde', 'Tete', 'Chifunde', 'neighbourhood', 0.0, 0.0),
('Mualadze', 'Tete', 'Chifunde', 'neighbourhood', 0.0, 0.0),
('Nsadzu', 'Tete', 'Chifunde', 'neighbourhood', 0.0, 0.0),
('Kazula', 'Tete', 'Chiuta', 'neighbourhood', 0.0, 0.0),
('Manje', 'Tete', 'Chiuta', 'neighbourhood', 0.0, 0.0),
('Cidade De Tete', 'Tete', 'Cidade De Tete', 'neighbourhood', 0.0, 0.0),
('Doa', 'Tete', 'Doa', 'neighbourhood', 0.0, 0.0),
('Chidzolomondo', 'Tete', 'Macanga', 'neighbourhood', 0.0, 0.0),
('Furancungo', 'Tete', 'Macanga', 'neighbourhood', 0.0, 0.0),
('Chinthopo', 'Tete', 'Magoe', 'neighbourhood', 0.0, 0.0),
('Mphende', 'Tete', 'Magoe', 'neighbourhood', 0.0, 0.0),
('Mukumbura', 'Tete', 'Magoe', 'neighbourhood', 0.0, 0.0),
('Marara', 'Tete', 'Marara', 'neighbourhood', 0.0, 0.0),
('Chipera', 'Tete', 'Maravia', 'neighbourhood', 0.0, 0.0),
('Chiputu', 'Tete', 'Maravia', 'neighbourhood', 0.0, 0.0),
('Fingoe', 'Tete', 'Maravia', 'neighbourhood', 0.0, 0.0),
('Malowera', 'Tete', 'Maravia', 'neighbourhood', 0.0, 0.0),
('Kambulatsisi', 'Tete', 'Moatize', 'neighbourhood', 0.0, 0.0),
('Moatize', 'Tete', 'Moatize', 'neighbourhood', 0.0, 0.0),
('Zobue', 'Tete', 'Moatize', 'neighbourhood', 0.0, 0.0),
('Charre', 'Tete', 'Mutarara', 'neighbourhood', 0.0, 0.0),
('Inhangoma', 'Tete', 'Mutarara', 'neighbourhood', 0.0, 0.0),
('Nhamayabue', 'Tete', 'Mutarara', 'neighbourhood', 0.0, 0.0),
('Ntengo-Wa-Mbalame', 'Tete', 'Tsangano', 'neighbourhood', 0.0, 0.0),
('Tsangano', 'Tete', 'Tsangano', 'neighbourhood', 0.0, 0.0),
('Muze', 'Tete', 'Zumbu', 'neighbourhood', 0.0, 0.0),
('Zambue', 'Tete', 'Zumbu', 'neighbourhood', 0.0, 0.0),
('Zumbu', 'Tete', 'Zumbu', 'neighbourhood', 0.0, 0.0),
('Alto Molocue', 'Zambezia', 'Alto Molocue', 'neighbourhood', 0.0, 0.0),
('Nauela', 'Zambezia', 'Alto Molocue', 'neighbourhood', 0.0, 0.0),
('Chinde', 'Zambezia', 'Chinde', 'neighbourhood', 0.0, 0.0),
('Micaune', 'Zambezia', 'Chinde', 'neighbourhood', 0.0, 0.0),
('Cidade De Quelimane', 'Zambezia', 'Cidade De Quelimane', 'neighbourhood', 0.0, 0.0),
('Derre', 'Zambezia', 'Derre', 'neighbourhood', 0.0, 0.0),
('Alto Ligonha', 'Zambezia', 'Gile', 'neighbourhood', 0.0, 0.0),
('Gile', 'Zambezia', 'Gile', 'neighbourhood', 0.0, 0.0),
('Gurue', 'Zambezia', 'Gurue', 'neighbourhood', 0.0, 0.0),
('Lioma', 'Zambezia', 'Gurue', 'neighbourhood', 0.0, 0.0),
('Mepuagiua', 'Zambezia', 'Gurue', 'neighbourhood', 0.0, 0.0),
('Ile', 'Zambezia', 'Ile', 'neighbourhood', 0.0, 0.0),
('Socone', 'Zambezia', 'Ile', 'neighbourhood', 0.0, 0.0),
('Gonhane', 'Zambezia', 'Inhassunge', 'neighbourhood', 0.0, 0.0),
('Inhassunge', 'Zambezia', 'Inhassunge', 'neighbourhood', 0.0, 0.0),
('Luabo', 'Zambezia', 'Luabo', 'neighbourhood', 0.0, 0.0),
('Lugela', 'Zambezia', 'Lugela', 'neighbourhood', 0.0, 0.0),
('Muabanama', 'Zambezia', 'Lugela', 'neighbourhood', 0.0, 0.0),
('Munhamade', 'Zambezia', 'Lugela', 'neighbourhood', 0.0, 0.0),
('Tacuane', 'Zambezia', 'Lugela', 'neighbourhood', 0.0, 0.0),
('Maganja', 'Zambezia', 'Maganja Da Costa', 'neighbourhood', 0.0, 0.0),
('Nante', 'Zambezia', 'Maganja Da Costa', 'neighbourhood', 0.0, 0.0),
('Maquival', 'Zambezia', 'Maquival', 'neighbourhood', 0.0, 0.0),
('Majaua', 'Zambezia', 'Milange', 'neighbourhood', 0.0, 0.0),
('Milange', 'Zambezia', 'Milange', 'neighbourhood', 0.0, 0.0),
('Mongue', 'Zambezia', 'Milange', 'neighbourhood', 0.0, 0.0),
('Mocuba', 'Zambezia', 'Mocuba', 'neighbourhood', 0.0, 0.0),
('Mugeba', 'Zambezia', 'Mocuba', 'neighbourhood', 0.0, 0.0),
('Namanjavira', 'Zambezia', 'Mocuba', 'neighbourhood', 0.0, 0.0),
('Bajone', 'Zambezia', 'Mocubela', 'neighbourhood', 0.0, 0.0),
('Mocubela', 'Zambezia', 'Mocubela', 'neighbourhood', 0.0, 0.0),
('Molumbo', 'Zambezia', 'Molumbo', 'neighbourhood', 0.0, 0.0),
('Campo', 'Zambezia', 'Mopeia', 'neighbourhood', 0.0, 0.0),
('Mopeia', 'Zambezia', 'Mopeia', 'neighbourhood', 0.0, 0.0),
('Chire', 'Zambezia', 'Morrumbala', 'neighbourhood', 0.0, 0.0),
('Megaza', 'Zambezia', 'Morrumbala', 'neighbourhood', 0.0, 0.0),
('Morrumbala', 'Zambezia', 'Morrumbala', 'neighbourhood', 0.0, 0.0),
('Mulevala', 'Zambezia', 'Mulevala', 'neighbourhood', 0.0, 0.0),
('Macuze', 'Zambezia', 'Namacurra', 'neighbourhood', 0.0, 0.0),
('Namacurra', 'Zambezia', 'Namacurra', 'neighbourhood', 0.0, 0.0),
('Namarroi', 'Zambezia', 'Namarroi', 'neighbourhood', 0.0, 0.0),
('Regone', 'Zambezia', 'Namarroi', 'neighbourhood', 0.0, 0.0),
('Nicoadala', 'Zambezia', 'Nicoadala', 'neighbourhood', 0.0, 0.0),
('Mualama', 'Zambezia', 'Pebane', 'neighbourhood', 0.0, 0.0),
('Naburi', 'Zambezia', 'Pebane', 'neighbourhood', 0.0, 0.0),
('Pebane', 'Zambezia', 'Pebane', 'neighbourhood', 0.0, 0.0),
